In [2]:
import sympy as sp
import numpy as np

# coord vs right, up

In [16]:
component = np.random.randn(2).reshape(2,1)
right = np.random.randn(2).reshape(2,1)
up = np.random.randn(2).reshape(2,1)
coord = np.hstack((right, up))
right, up , coord

(array([[-0.28849013],
        [-0.69813918]]),
 array([[-0.02416202],
        [-0.12259081]]),
 array([[-0.28849013, -0.02416202],
        [-0.69813918, -0.12259081]]))

In [6]:
%%timeit 
coord @ component

1.14 µs ± 9.92 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
%%timeit
right * component[0] + up * component[1]

3.19 µs ± 19.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
%%timeit
x,y= component
right * x + up * y

3.79 µs ± 167 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
%%timeit
x,y= component

683 ns ± 5.49 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
x,y= component

In [18]:
%%timeit
right * x + up * y

2.9 µs ± 168 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
%%timeit
np.hstack([right,up])@np.array([x,y])

8.04 µs ± 435 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
%%timeit
component = np.random.randn(2).reshape(2,1)
right = np.random.randn(2).reshape(2,1)
up = np.random.randn(2).reshape(2,1)
coord = np.hstack((right, up))

6.89 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
%%timeit
component = np.random.randn(2)
right = np.random.randn(2)
up = np.random.randn(2)
coord = np.vstack((right, up))

6.87 µs ± 95.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
%%timeit
component = np.random.randn(2)

786 ns ± 34.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
%%timeit
coord = np.vstack((right, up))

3.61 µs ± 293 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# lambdafiy vs matrix multiplication

In [3]:
m11,m12,m21,m22=sp.symbols('m11,m12,m21,m22')
M=sp.Matrix([[m11,m12],[m21,m22]])
v1,v2=sp.symbols('v1,v2')
v=sp.Matrix([[v1],[v2]])
M,v

(Matrix([
 [m11, m12],
 [m21, m22]]),
 Matrix([
 [v1],
 [v2]]))

In [11]:
%%timeit
M*v

52.3 µs ± 2.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
Mv_num=sp.lambdify([(v1,v2),(m11,m12,m21,m22)],M*v,modules='numpy')

In [7]:
print(Mv_num.__doc__)

Created with lambdify. Signature:

func(arg_0, arg_1)

Expression:

Matrix([[m11*v1 + m12*v2], [m21*v1 + m22*v2]])

Source code:

def _lambdifygenerated(_Dummy_22, _Dummy_23):
    [v1, v2] = _Dummy_22
    [m11, m12, m21, m22] = _Dummy_23
    return array([[m11*v1 + m12*v2], [m21*v1 + m22*v2]])


Imported modules:




In [5]:
%%timeit
Mv_num=sp.lambdify([(v1,v2),(m11,m12,m21,m22)],M*v,modules='numpy')

2.47 ms ± 188 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
v1_num,v2_num,m11_num,m12_num,m21_num,m22_num = np.random.rand(6)

In [10]:
%%timeit
M_num=M.evalf(subs={m11:m11_num,m12:m12_num,m21:m21_num,m22:m22_num})
v_num=v.evalf(subs={v1:v1_num,v2:v2_num})
M_num@v_num

591 µs ± 16.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [22]:
%%timeit
M_num=np.array([[m11_num,m12_num],[m21_num,m22_num]])
v_num=np.array([v1_num,v2_num])

2.34 µs ± 72.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
M_num=np.array([[m11_num,m12_num],[m21_num,m22_num]])
v_num=np.array([v1_num,v2_num])

In [20]:
%%timeit
M_num@v_num

1.04 µs ± 4.22 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
%%timeit
Mv_num((v1_num, v2_num),(m11_num, m12_num, m21_num, m22_num))

TypeError: _lambdifygenerated() missing 4 required positional arguments: 'm11', 'm12', 'm21', and 'm22'

In [16]:
Mv_num=sp.lambdify([v1,v2,m11,m12,m21,m22],M*v,modules='numpy')

In [17]:
print(Mv_num.__doc__)


Created with lambdify. Signature:

func(v1, v2, m11, m12, m21, m22)

Expression:

Matrix([[m11*v1 + m12*v2], [m21*v1 + m22*v2]])

Source code:

def _lambdifygenerated(v1, v2, m11, m12, m21, m22):
    return array([[m11*v1 + m12*v2], [m21*v1 + m22*v2]])


Imported modules:




In [19]:
%%timeit
Mv_num(v1_num, v2_num,m11_num, m12_num, m21_num, m22_num)

2.12 µs ± 54.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
%%timeit
np.array([[m11_num*v1_num + m12_num*v2_num], [m21_num*v1_num + m22_num*v2_num]])

2.02 µs ± 58.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%%timeit
np.array(((m11_num*v1_num + m12_num*v2_num), (m21_num*v1_num + m22_num*v2_num)))

1.1 µs ± 1.66 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [25]:
%%timeit
np.array((m11_num*v1_num + m12_num*v2_num, m21_num*v1_num + m22_num*v2_num))

1.12 µs ± 12.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [36]:
%%timeit
m11_num*v1_num + m12_num*v2_num
m21_num*v1_num + m22_num*v2_num

442 ns ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [35]:
M_list=((m11_num,m12_num),(m21_num,m22_num))
v_list=(v1,v2)

In [33]:
%%timeit
M_list=((m11_num,m12_num),(m21_num,m22_num))
v_list=(v1,v2)

177 ns ± 0.883 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [31]:
%%timeit
M_list=[[m11_num,m12_num],[m21_num,m22_num]]
v_list=[v1,v2]

202 ns ± 0.602 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [32]:
%%timeit
M_list[0][0]*v_list[0] + M_list[0][1]*v_list[1]
M_list[1][0]*v_list[0] + M_list[1][1]*v_list[1]

108 µs ± 5.34 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [37]:
%%timeit
M1,M2=M_list
m11,m12=M1
m21,m22=M2
v1,v2=v_list
m11*v1 + m12*v2
m21*v1 + m22*v2

110 µs ± 5.37 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [26]:
%%timeit
np.array((1,1))

652 ns ± 6.29 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [41]:
import sympy as sp
x , y = sp.symbols ('x, y')

expr = [x*y]
f1 = sp.lambdify([x,y], expr)
f2 = sp.lambdify([[x,y]], expr)

%timeit f1(3,4)
%timeit f2([3,4])

131 ns ± 1.54 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
174 ns ± 1.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [42]:
%timeit f1(3,4)
%timeit f2((3,4))

135 ns ± 4.66 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
151 ns ± 8.71 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [43]:
print(f1.__doc__)
print(f2.__doc__)

Created with lambdify. Signature:

func(x, y)

Expression:

[x*y]

Source code:

def _lambdifygenerated(x, y):
    return [x*y]


Imported modules:


Created with lambdify. Signature:

func(arg_0)

Expression:

[x*y]

Source code:

def _lambdifygenerated(_Dummy_1647):
    [x, y] = _Dummy_1647
    return [x*y]


Imported modules:




In [ ]:
def matrix_mul(a,b):
    a11, a12, a21, a22 = a
    b11, b12, b21, b22 = b
    return (a11*b11 + a12*b21, a11*b12 + a12*b22, a21*b11 + a22*b21, a21*b12 + a22*b22)

In [44]:
a=np.random.rand(4)
b=np.random.rand(4)

In [46]:
%%timeit
a11, a12, a21, a22 = a
b11, b12, b21, b22 = b
a11*b11 + a12*b21
a11*b12 + a12*b22
a21*b11 + a22*b21
a21*b12 + a22*b22

2.13 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [49]:
A=a.reshape((2,2))
B=b.reshape((2,2))

In [50]:
%%timeit
A@B

1.45 µs ± 12.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [2]:
import numpy as np

In [13]:
edge_num=10
theta = np.linspace(0, 2*np.pi, edge_num)
theta


array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [5]:
np.cos(theta)

array([ 1.        ,  0.76604444,  0.17364818, -0.5       , -0.93969262,
       -0.93969262, -0.5       ,  0.17364818,  0.76604444,  1.        ])

In [6]:
up=np.array([0,1])
right=np.array([1,0])
up, right

(array([0, 1]), array([1, 0]))

In [7]:
print(f"theta shape: {theta.shape}")
print(f"up shape: {up.shape}")
print(f"right shape: {right.shape}")


theta shape: (10,)
up shape: (2,)
right shape: (2,)


In [8]:
unit_circle = right*np.cos(theta)+up*np.sin(theta)

ValueError: operands could not be broadcast together with shapes (2,) (10,) 

In [9]:
theta_reshaped = theta.reshape(-1, 1)
print(f"theta_reshaped.shape: {theta_reshaped.shape}")
print(f"theta_reshaped: {theta_reshaped}")

theta_reshaped.shape: (10, 1)
theta_reshaped: [[0.        ]
 [0.6981317 ]
 [1.3962634 ]
 [2.0943951 ]
 [2.7925268 ]
 [3.4906585 ]
 [4.1887902 ]
 [4.88692191]
 [5.58505361]
 [6.28318531]]


In [10]:
unit_circle = right*np.cos(theta_reshaped)+up*np.sin(theta_reshaped)
unit_circle

array([[ 1.00000000e+00,  0.00000000e+00],
       [ 7.66044443e-01,  6.42787610e-01],
       [ 1.73648178e-01,  9.84807753e-01],
       [-5.00000000e-01,  8.66025404e-01],
       [-9.39692621e-01,  3.42020143e-01],
       [-9.39692621e-01, -3.42020143e-01],
       [-5.00000000e-01, -8.66025404e-01],
       [ 1.73648178e-01, -9.84807753e-01],
       [ 7.66044443e-01, -6.42787610e-01],
       [ 1.00000000e+00, -2.44929360e-16]])

In [14]:
import numpy as np

In [17]:
width , height = 10000, 0.01
star_num = 10
star_pos_list = np.random.uniform(0, [width,height], (star_num, 2))
star_pos_list

array([[6.76891853e+03, 4.13430313e-04],
       [9.91437594e+03, 1.73430534e-03],
       [6.21510266e+03, 1.90939789e-03],
       [7.90005190e+03, 1.51232386e-03],
       [8.86179873e+03, 2.31430124e-03],
       [1.50756042e+03, 7.11275309e-03],
       [9.49204910e+03, 6.48866107e-03],
       [9.25902246e+03, 7.51342397e-03],
       [9.94523985e+02, 2.58552642e-03],
       [7.14897010e+03, 5.90246619e-03]])

In [19]:
star_size_list = np.random.uniform(0.00, 0.03, star_num)
star_size_list

array([0.00536452, 0.00595798, 0.00641257, 0.02926652, 0.01043846,
       0.01447819, 0.00971873, 0.02801628, 0.009473  , 0.00905035])

In [21]:
can_see = star_size_list > 0.01
can_see

array([False, False, False,  True,  True,  True, False,  True, False,
       False])

In [22]:
star_pos_list[can_see]

array([[7.90005190e+03, 1.51232386e-03],
       [8.86179873e+03, 2.31430124e-03],
       [1.50756042e+03, 7.11275309e-03],
       [9.25902246e+03, 7.51342397e-03]])

In [24]:
right_edges = star_pos_list[:,1] + star_size_list
right_edges

array([0.00577795, 0.00769229, 0.00832197, 0.03077884, 0.01275276,
       0.02159094, 0.01620739, 0.0355297 , 0.01205852, 0.01495282])

In [3]:
a=(1,2)
b=(3,4)
c=(*a,*b)
c

(1, 2, 3, 4)

In [23]:
import numpy as np
a=np.arange(99)
a[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [29]:
a[::4]

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [1]:
import sympy as sp

In [2]:
gp11,gp12,gp21,gp22,gq11,gq12,gq21,gq22 = sp.symbols('g_{p11} g_{p12} g_{p21} g_{p22} g_{q11} g_{q12} g_{q21} g_{q22}',real=True)
x,y,x0,y0,x1,y1,x2,y2 = sp.symbols('x y x_0 y_0 x_1 y_1 x_2 y_2',real=True)
lam=sp.symbols('lambda',real=True)
gp = sp.Matrix([[gp11,gp12],[gp21,gp22]])
gq = sp.Matrix([[gq11,gq12],[gq21,gq22]])
B = sp.Matrix([[x],[y]])
P = sp.Matrix([[x0],[y0]])
Q = sp.Matrix([[x1],[y1]])

In [3]:
(B-P).T*gp*(B-P)

Matrix([[(x - x_0)*(g_{p11}*(x - x_0) + g_{p21}*(y - y_0)) + (y - y_0)*(g_{p12}*(x - x_0) + g_{p22}*(y - y_0))]])

In [4]:
# nable gp(B-P,B-P)=lambda*nable gq(B-Q,B-Q)
# gq(B-Q,B-Q)=1
f=((B-P).T*gp*(B-P))[0]
g=((B-Q).T*gq*(B-Q))[0]-1
eqs=[
    sp.Eq(f.diff(x),lam*g.diff(x)),
    sp.Eq(f.diff(y),lam*g.diff(y)),
    # sp.Eq(g,0)
]
for eq in eqs:
    display(eq)

Eq(2*g_{p11}*(x - x_0) + g_{p12}*(y - y_0) + g_{p21}*(y - y_0), lambda*(2*g_{q11}*(x - x_1) + g_{q12}*(y - y_1) + g_{q21}*(y - y_1)))

Eq(g_{p12}*(x - x_0) + g_{p21}*(x - x_0) + 2*g_{p22}*(y - y_0), lambda*(g_{q12}*(x - x_1) + g_{q21}*(x - x_1) + 2*g_{q22}*(y - y_1)))

In [5]:
sol=sp.solve(eqs,[x,y],dict=True)[0]
sol

{x: (4*g_{p11}*g_{p22}*x_0 - 4*g_{p11}*g_{q22}*lambda*x_0 - g_{p12}**2*x_0 - 2*g_{p12}*g_{p21}*x_0 + g_{p12}*g_{q12}*lambda*x_0 + g_{p12}*g_{q12}*lambda*x_1 + g_{p12}*g_{q21}*lambda*x_0 + g_{p12}*g_{q21}*lambda*x_1 - 2*g_{p12}*g_{q22}*lambda*y_0 + 2*g_{p12}*g_{q22}*lambda*y_1 - g_{p21}**2*x_0 + g_{p21}*g_{q12}*lambda*x_0 + g_{p21}*g_{q12}*lambda*x_1 + g_{p21}*g_{q21}*lambda*x_0 + g_{p21}*g_{q21}*lambda*x_1 - 2*g_{p21}*g_{q22}*lambda*y_0 + 2*g_{p21}*g_{q22}*lambda*y_1 - 4*g_{p22}*g_{q11}*lambda*x_1 + 2*g_{p22}*g_{q12}*lambda*y_0 - 2*g_{p22}*g_{q12}*lambda*y_1 + 2*g_{p22}*g_{q21}*lambda*y_0 - 2*g_{p22}*g_{q21}*lambda*y_1 + 4*g_{q11}*g_{q22}*lambda**2*x_1 - g_{q12}**2*lambda**2*x_1 - 2*g_{q12}*g_{q21}*lambda**2*x_1 - g_{q21}**2*lambda**2*x_1)/(4*g_{p11}*g_{p22} - 4*g_{p11}*g_{q22}*lambda - g_{p12}**2 - 2*g_{p12}*g_{p21} + 2*g_{p12}*g_{q12}*lambda + 2*g_{p12}*g_{q21}*lambda - g_{p21}**2 + 2*g_{p21}*g_{q12}*lambda + 2*g_{p21}*g_{q21}*lambda - 4*g_{p22}*g_{q11}*lambda + 4*g_{q11}*g_{q22}*lam

In [6]:
for key,value in sol.items():
    display(key)
    display(value)

x

(4*g_{p11}*g_{p22}*x_0 - 4*g_{p11}*g_{q22}*lambda*x_0 - g_{p12}**2*x_0 - 2*g_{p12}*g_{p21}*x_0 + g_{p12}*g_{q12}*lambda*x_0 + g_{p12}*g_{q12}*lambda*x_1 + g_{p12}*g_{q21}*lambda*x_0 + g_{p12}*g_{q21}*lambda*x_1 - 2*g_{p12}*g_{q22}*lambda*y_0 + 2*g_{p12}*g_{q22}*lambda*y_1 - g_{p21}**2*x_0 + g_{p21}*g_{q12}*lambda*x_0 + g_{p21}*g_{q12}*lambda*x_1 + g_{p21}*g_{q21}*lambda*x_0 + g_{p21}*g_{q21}*lambda*x_1 - 2*g_{p21}*g_{q22}*lambda*y_0 + 2*g_{p21}*g_{q22}*lambda*y_1 - 4*g_{p22}*g_{q11}*lambda*x_1 + 2*g_{p22}*g_{q12}*lambda*y_0 - 2*g_{p22}*g_{q12}*lambda*y_1 + 2*g_{p22}*g_{q21}*lambda*y_0 - 2*g_{p22}*g_{q21}*lambda*y_1 + 4*g_{q11}*g_{q22}*lambda**2*x_1 - g_{q12}**2*lambda**2*x_1 - 2*g_{q12}*g_{q21}*lambda**2*x_1 - g_{q21}**2*lambda**2*x_1)/(4*g_{p11}*g_{p22} - 4*g_{p11}*g_{q22}*lambda - g_{p12}**2 - 2*g_{p12}*g_{p21} + 2*g_{p12}*g_{q12}*lambda + 2*g_{p12}*g_{q21}*lambda - g_{p21}**2 + 2*g_{p21}*g_{q12}*lambda + 2*g_{p21}*g_{q21}*lambda - 4*g_{p22}*g_{q11}*lambda + 4*g_{q11}*g_{q22}*lambda*

y

(4*g_{p11}*g_{p22}*y_0 + 2*g_{p11}*g_{q12}*lambda*x_0 - 2*g_{p11}*g_{q12}*lambda*x_1 + 2*g_{p11}*g_{q21}*lambda*x_0 - 2*g_{p11}*g_{q21}*lambda*x_1 - 4*g_{p11}*g_{q22}*lambda*y_1 - g_{p12}**2*y_0 - 2*g_{p12}*g_{p21}*y_0 - 2*g_{p12}*g_{q11}*lambda*x_0 + 2*g_{p12}*g_{q11}*lambda*x_1 + g_{p12}*g_{q12}*lambda*y_0 + g_{p12}*g_{q12}*lambda*y_1 + g_{p12}*g_{q21}*lambda*y_0 + g_{p12}*g_{q21}*lambda*y_1 - g_{p21}**2*y_0 - 2*g_{p21}*g_{q11}*lambda*x_0 + 2*g_{p21}*g_{q11}*lambda*x_1 + g_{p21}*g_{q12}*lambda*y_0 + g_{p21}*g_{q12}*lambda*y_1 + g_{p21}*g_{q21}*lambda*y_0 + g_{p21}*g_{q21}*lambda*y_1 - 4*g_{p22}*g_{q11}*lambda*y_0 + 4*g_{q11}*g_{q22}*lambda**2*y_1 - g_{q12}**2*lambda**2*y_1 - 2*g_{q12}*g_{q21}*lambda**2*y_1 - g_{q21}**2*lambda**2*y_1)/(4*g_{p11}*g_{p22} - 4*g_{p11}*g_{q22}*lambda - g_{p12}**2 - 2*g_{p12}*g_{p21} + 2*g_{p12}*g_{q12}*lambda + 2*g_{p12}*g_{q21}*lambda - g_{p21}**2 + 2*g_{p21}*g_{q12}*lambda + 2*g_{p21}*g_{q21}*lambda - 4*g_{p22}*g_{q11}*lambda + 4*g_{q11}*g_{q22}*lambda*

In [9]:
sp.collect(sol[x],lam)

(4*g_{p11}*g_{p22}*x_0 - g_{p12}**2*x_0 - 2*g_{p12}*g_{p21}*x_0 - g_{p21}**2*x_0 + lambda**2*(4*g_{q11}*g_{q22}*x_1 - g_{q12}**2*x_1 - 2*g_{q12}*g_{q21}*x_1 - g_{q21}**2*x_1) + lambda*(-4*g_{p11}*g_{q22}*x_0 + g_{p12}*g_{q12}*x_0 + g_{p12}*g_{q12}*x_1 + g_{p12}*g_{q21}*x_0 + g_{p12}*g_{q21}*x_1 - 2*g_{p12}*g_{q22}*y_0 + 2*g_{p12}*g_{q22}*y_1 + g_{p21}*g_{q12}*x_0 + g_{p21}*g_{q12}*x_1 + g_{p21}*g_{q21}*x_0 + g_{p21}*g_{q21}*x_1 - 2*g_{p21}*g_{q22}*y_0 + 2*g_{p21}*g_{q22}*y_1 - 4*g_{p22}*g_{q11}*x_1 + 2*g_{p22}*g_{q12}*y_0 - 2*g_{p22}*g_{q12}*y_1 + 2*g_{p22}*g_{q21}*y_0 - 2*g_{p22}*g_{q21}*y_1))/(4*g_{p11}*g_{p22} - g_{p12}**2 - 2*g_{p12}*g_{p21} - g_{p21}**2 + lambda**2*(4*g_{q11}*g_{q22} - g_{q12}**2 - 2*g_{q12}*g_{q21} - g_{q21}**2) + lambda*(-4*g_{p11}*g_{q22} + 2*g_{p12}*g_{q12} + 2*g_{p12}*g_{q21} + 2*g_{p21}*g_{q12} + 2*g_{p21}*g_{q21} - 4*g_{p22}*g_{q11}))